<a href="https://colab.research.google.com/github/nan-park/section2_project/blob/main/data_modeling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statsmodels.tsa.stattools import adfuller

In [2]:
from google.colab import files
files.upload();
# kor_economic_monthly_data_clean.csv
# us_economic_monthly_data_clean.csv

Saving kor_economic_monthly_data_clean.csv to kor_economic_monthly_data_clean.csv
Saving us_economic_monthly_data_clean.csv to us_economic_monthly_data_clean.csv

In [7]:
url1 = 'kor_economic_monthly_data_clean.csv'
url2 = 'us_economic_monthly_data_clean.csv'
kor_df = pd.read_csv(url1, index_col=0)
us_df = pd.read_csv(url2, index_col=0)

# **데이터 전처리**

In [9]:
kor_df # 1999-05 ~ 2022-05

,기준금리(연%),가계대출금리(연%),소비자물가지수_총(2020=100),원화환율(원/달러),주택매매가격지수(2022.01=100),콜금리(연%),국고채3년금리(연%),경제성장률,실업률(%),외환보유액_총(천달러),외환보유액_금(천달러),외환보유액_특별인출권(천달러),외환보유액_IMF포지션(천달러),외환보유액_예치금및유가증권(천달러)
1999-05-01,4.75,11.00,61.712,1197.00,38.374,4.800,6.750,4.400000,6.8,61409325.0,66683.0,10831.0,280487.0,61051324.0
1999-06-01,4.75,10.46,61.349,1169.63,38.374,4.810,6.880,3.866667,7.3,61987062.0,66683.0,11556.0,278952.0,61629871.0
1999-07-01,4.75,10.31,61.140,1186.04,38.498,4.840,7.890,3.333333,7.0,64944463.0,66683.0,11787.0,284546.0,64581447.0
1999-08-01,4.75,10.22,61.765,1199.79,38.747,4.750,8.910,2.800000,6.4,64782273.0,66683.0,14706.0,283925.0,64416959.0
1999-09-01,4.75,10.21,61.921,1196.97,39.037,4.740,9.330,2.833333,5.7,65480127.0,66683.0,14909.0,287843.0,65110692.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-01-01,1.25,3.91,104.690,1194.01,100.000,1.181,2.060,0.833333,3.6,461526656.0,4794759.0,15288832.0,4606897.0,436836167.0
2022-02-01,1.25,3.93,105.300,1198.34,100.207,1.211,2.285,0.600000,2.7,461766293.0,4794759.0,15313847.0,4614178.0,437043509.0
2022-03-01,1.25,3.98,106.060,1221.03,100.306,1.250,2.369,0.633333,2.7,457810337.0,4794759.0,15415450.0,4578104.0,433022025.0
2022-04-01,1.50,4.05,106.850,1232.34,100.517,1.297,2.941,0.666667,2.7,449297713.0,4794759.0,14977119.0,4449074.0,425076761.0
2022-05-01,1.75,4.14,107.560,1269.88,100.768,1.504,3.019,0.700000,2.8,447711119.0,4794759.0,15081254.0,4479955.0,423355152.0

한국의 데이터를 주로 하되, 미국의 기준금리도 중요한 feature이기에 넣어준다.

In [16]:
date_index = kor_df.index
df = kor_df.copy()
df['미국_기준금리(연%)'] = us_df.loc[date_index, 'funds_rate']
df.head()

,기준금리(연%),가계대출금리(연%),소비자물가지수_총(2020=100),원화환율(원/달러),주택매매가격지수(2022.01=100),콜금리(연%),국고채3년금리(연%),경제성장률,실업률(%),외환보유액_총(천달러),외환보유액_금(천달러),외환보유액_특별인출권(천달러),외환보유액_IMF포지션(천달러),외환보유액_예치금및유가증권(천달러),미국_기준금리(연%)
1999-05-01,4.75,11.00,61.712,1197.00,38.374,4.80,6.75,4.400000,6.8,61409325.0,66683.0,10831.0,280487.0,61051324.0,4.742258
1999-06-01,4.75,10.46,61.349,1169.63,38.374,4.81,6.88,3.866667,7.3,61987062.0,66683.0,11556.0,278952.0,61629871.0,4.764667
1999-07-01,4.75,10.31,61.140,1186.04,38.498,4.84,7.89,3.333333,7.0,64944463.0,66683.0,11787.0,284546.0,64581447.0,4.994194
1999-08-01,4.75,10.22,61.765,1199.79,38.747,4.75,8.91,2.800000,6.4,64782273.0,66683.0,14706.0,283925.0,64416959.0,5.072258
1999-09-01,4.75,10.21,61.921,1196.97,39.037,4.74,9.33,2.833333,5.7,65480127.0,66683.0,14909.0,287843.0,65110692.0,5.224333

소비자물가지수 -> 소비자물가상승률(consumer inflation rate)<br>
보통 물가상승률은 전년동월대비 상승률로 표시한다.<br>
물가상승률 = (금월 물가지수 - 전년동월 물가지수) / 전년동월 물가지수 * 100

In [56]:
df_added = df.copy()
date_index = df.index
cpi_col = '소비자물가지수_총(2020=100)'
for i in range(len(date_index)):
  if i not in [0, 11]:  # 처음 년도 인덱스는 제외
    present_date_i = df.index[i]
    past_date_i = df.index[i-12]
    present = df.loc[present_date_i, cpi_col]
    past = df.loc[past_date_i, cpi_col]
    temp = (present - past) / past * 100  # 물가상승률
    df_added.loc[present_date_i, cpi_col] = temp
df_added.drop(df_added.index[0:12], inplace=True)

In [57]:
df_added.rename(columns={cpi_col:'소비자물가상승률(%)'}, inplace=True);
df_added.head()

,기준금리(연%),가계대출금리(연%),소비자물가상승률(%),원화환율(원/달러),주택매매가격지수(2022.01=100),콜금리(연%),국고채3년금리(연%),경제성장률,실업률(%),외환보유액_총(천달러),외환보유액_금(천달러),외환보유액_특별인출권(천달러),외환보유액_IMF포지션(천달러),외환보유액_예치금및유가증권(천달러),미국_기준금리(연%)
2000-05-01,5.0,9.96,1.103513,1120.01,39.327,5.13,8.96,1.300000,4.3,86819839.0,67379.0,4846.0,276348.0,86471266.0,6.268065
2000-06-01,5.0,9.87,2.216825,1118.73,39.203,5.14,8.66,1.800000,4.2,90178599.0,67379.0,4073.0,278818.0,89828329.0,6.528333
2000-07-01,5.0,9.92,2.980046,1114.86,39.203,5.16,8.00,2.300000,4.1,90353996.0,67379.0,83432.0,274609.0,89928576.0,6.544516
2000-08-01,5.0,9.77,2.447988,1114.57,39.285,5.17,7.85,2.800000,4.2,91434450.0,67379.0,6912.0,271673.0,91088486.0,6.496774
2000-09-01,5.0,9.76,3.515770,1116.50,39.368,5.16,7.96,1.766667,4.4,92534872.0,67631.0,6889.0,270780.0,92189572.0,6.517000

In [58]:
df_added.tail()

,기준금리(연%),가계대출금리(연%),소비자물가상승률(%),원화환율(원/달러),주택매매가격지수(2022.01=100),콜금리(연%),국고채3년금리(연%),경제성장률,실업률(%),외환보유액_총(천달러),외환보유액_금(천달러),외환보유액_특별인출권(천달러),외환보유액_IMF포지션(천달러),외환보유액_예치금및유가증권(천달러),미국_기준금리(연%)
2022-01-01,1.25,3.91,3.612431,1194.01,100.000,1.181,2.060,0.833333,3.6,461526656.0,4794759.0,15288832.0,4606897.0,436836167.0,0.080000
2022-02-01,1.25,3.93,3.662138,1198.34,100.207,1.211,2.285,0.600000,2.7,461766293.0,4794759.0,15313847.0,4614178.0,437043509.0,0.080000
2022-03-01,1.25,3.98,4.143755,1221.03,100.306,1.250,2.369,0.633333,2.7,457810337.0,4794759.0,15415450.0,4578104.0,433022025.0,0.199565
2022-04-01,1.50,4.05,4.775446,1232.34,100.517,1.297,2.941,0.666667,2.7,449297713.0,4794759.0,14977119.0,4449074.0,425076761.0,0.330000
2022-05-01,1.75,4.14,5.399314,1269.88,100.768,1.504,3.019,0.700000,2.8,447711119.0,4794759.0,15081254.0,4479955.0,423355152.0,0.758571

In [61]:
# 드라이브에 저장
# import sys

# if "google.colab" in sys.modules:
#     from google.colab import drive
#     drive.mount('/content/drive')
df_added.to_csv("/content/drive/MyDrive/model_data.csv")  # 소비자물가상승률 포함 데이터(모델링 전에 최종 전처리)

In [38]:
# 과거 데이터가 현재 데이터에 영향을 미친다는 합리적 판단?

시계열 데이터이므로, 시계열 분석에 맞는 모델을 만들어야 한다.<br>
먼저 정상성을 지닌 시계열 데이터로 바꾸고자 한다.(정상성 체크 by ADF test)

In [62]:
df = df_added.copy()  # 다시 대체해준다

In [63]:
# from statsmodels.tsa.stattools import adfuller
def adf_test(y):
  dftest = adfuller(y, autolag='AIC')
  pvalue = dftest[1]
  return pvalue
unsatisfied_cols = []
for col in df.columns:
  print(f"{col}: {adf_test(df[col]).round(4)}")
print()
for col in df.columns:
  print(f"{col}: {adf_test(df[col])<0.05}") # True면 정상성 만족
  if adf_test(df[col]) >= 0.05: # unsatisfied
    unsatisfied_cols.append(col)

기준금리(연%): 0.2731
가계대출금리(연%): 0.0507
소비자물가상승률(%): 0.1812
원화환율(원/달러): 0.0421
주택매매가격지수(2022.01=100): 0.9316
콜금리(연%): 0.2858
국고채3년금리(연%): 0.3144
경제성장률: 0.0002
실업률(%): 0.0048
외환보유액_총(천달러): 0.5982
외환보유액_금(천달러): 0.6219
외환보유액_특별인출권(천달러): 0.9644
외환보유액_IMF포지션(천달러): 0.9837
외환보유액_예치금및유가증권(천달러): 0.4638
미국_기준금리(연%): 0.003

기준금리(연%): False
가계대출금리(연%): False
소비자물가상승률(%): False
원화환율(원/달러): True
주택매매가격지수(2022.01=100): False
콜금리(연%): False
국고채3년금리(연%): False
경제성장률: True
실업률(%): True
외환보유액_총(천달러): False
외환보유액_금(천달러): False
외환보유액_특별인출권(천달러): False
외환보유액_IMF포지션(천달러): False
외환보유액_예치금및유가증권(천달러): False
미국_기준금리(연%): True

환율, 경제성장률, 실업률, 미국 기준금리 제외하고 모두 정상성을 띠지 않는다.

In [64]:
unsatisfied_cols  # 정상성을 만족하지 않는 컬럼들

['기준금리(연%)',
 '가계대출금리(연%)',
 '소비자물가상승률(%)',
 '주택매매가격지수(2022.01=100)',
 '콜금리(연%)',
 '국고채3년금리(연%)',
 '외환보유액_총(천달러)',
 '외환보유액_금(천달러)',
 '외환보유액_특별인출권(천달러)',
 '외환보유액_IMF포지션(천달러)',
 '외환보유액_예치금및유가증권(천달러)']

unsatisfied_cols는 차분해준다.(금월 값 - 전월 값)(변화량)

In [67]:
date_index = df.index
df_stat = df.copy() # 정상성 띠도록 만든 데이터(stationary)

for i in range(len(date_index)):
  if i != 0:  #i==0일 때는 변화량 계산 불가
    present_date_i = df.index[i]
    past_date_i = df.index[i-1]
    present = df.loc[present_date_i, unsatisfied_cols]
    past = df.loc[past_date_i, unsatisfied_cols]
    temp = present - past # 변화량
    df_stat.loc[present_date_i, unsatisfied_cols] = temp

In [68]:
for col_i in range(len(df_stat.columns)):
  print(f"{df_stat.columns[col_i]}: {adf_test(df_stat.iloc[1:, col_i])<0.05}") # 0번째 인덱스는 변화량이 되지 않았으므로 제외함

기준금리(연%): True
가계대출금리(연%): True
소비자물가상승률(%): True
원화환율(원/달러): True
주택매매가격지수(2022.01=100): True
콜금리(연%): True
국고채3년금리(연%): True
경제성장률: True
실업률(%): True
외환보유액_총(천달러): True
외환보유액_금(천달러): False
외환보유액_특별인출권(천달러): True
외환보유액_IMF포지션(천달러): True
외환보유액_예치금및유가증권(천달러): True
미국_기준금리(연%): True

외환보유액_금(천달러)만 정상성 만족하지 않음.<br>
이 컬럼은 2차 차분해준다.(변화량의 변화량)

In [69]:
df_stat.drop(df_stat.index[0], inplace=True)  # 0번째 인덱스는 제거해준다

In [70]:
date_index = df_stat.index
df_stat_second = df_stat.copy()
second_unsatisfied_cols = ['외환보유액_금(천달러)']
for i in range(len(date_index)):
  if i != 0:  # 0번째면 제외
    present_date_i = df_stat.index[i]
    past_date_i = df_stat.index[i-1]
    present = df_stat.loc[present_date_i, second_unsatisfied_cols]
    past = df_stat.loc[past_date_i, second_unsatisfied_cols]
    temp = present - past
    df_stat_second.loc[present_date_i, second_unsatisfied_cols] = temp

In [71]:
for col_i in range(len(df_stat_second.columns)):
  print(f"{df_stat_second.columns[col_i]}: {adf_test(df_stat_second.iloc[1:, col_i])<0.05}") # 0번째 인덱스는 변화량이 되지 않았으므로 제외함

기준금리(연%): True
가계대출금리(연%): True
소비자물가상승률(%): True
원화환율(원/달러): True
주택매매가격지수(2022.01=100): True
콜금리(연%): True
국고채3년금리(연%): True
경제성장률: True
실업률(%): True
외환보유액_총(천달러): True
외환보유액_금(천달러): True
외환보유액_특별인출권(천달러): True
외환보유액_IMF포지션(천달러): True
외환보유액_예치금및유가증권(천달러): True
미국_기준금리(연%): True

이제 모든 컬럼이 정상성을 띠게 되었다.(df_stat_second)

In [72]:
df_stat_second.to_csv("/content/drive/MyDrive/model_data_stationary.csv")