<a href="https://colab.research.google.com/github/nan-park/section2_project/blob/main/kor_data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from google.colab import files
files.upload();

Saving kor_overall_data.csv to kor_overall_data.csv

In [3]:
url = 'kor_overall_data.csv'
kor_overall_df = pd.read_csv(url).T

In [4]:
kor_overall_df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
통계표,1.3.1. 한국은행 기준금리 및 여수신금리,1.3.3.2.1. 예금은행 대출금리(신규취급액 기준),3.5. 외환보유액,4.1.1.2. 생산자물가지수(특수분류),4.1.1.1. 생산자물가지수(기본분류),4.1.2. 국내공급물가지수,4.2.2. 소비자물가지수(특수분류),4.2.2. 소비자물가지수(특수분류),4.2.2. 소비자물가지수(특수분류),4.3.1.2. 수출물가지수(특수분류),4.3.1.2. 수출물가지수(특수분류),4.3.1.2. 수출물가지수(특수분류),4.3.2.2. 수입물가지수(특수분류),4.3.2.2. 수입물가지수(특수분류),4.3.2.2. 수입물가지수(특수분류),3.1.2.1. 주요국 통화의 대원화환율,4.4.1.1. 주택매매가격지수(KB),"1.3.2.2. 시장금리(월,분기,년)","1.3.2.2. 시장금리(월,분기,년)"
항목명1,한국은행 기준금리,가계대출,외환,식료품에너지이외,총지수,원재료,총지수,식료품 및 에너지제외 지수 3),생활물가지수 4),총지수,식료품에너지,식료품에너지이외,총지수,식료품에너지,식료품에너지이외,원/미국달러(매매기준율),총지수,무담보콜금리 전체,국고채(3년)
항목명2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,계약통화기준,계약통화기준,계약통화기준,계약통화기준,계약통화기준,계약통화기준,평균자료,NaN,NaN,NaN
단위,연%,연리%,천달러,2015=100,2015=100,2015=100,2020=100,2020=100,2020=100,2015=100,2015=100,2015=100,2015=100,2015=100,2015=100,원,2022.01=100,연%,연%
가중치,NaN,NaN,NaN,858.2,1000.0,88.266,1000.0,776.5,529.4,1000.0,92.6,907.4,1000.0,340.6,659.4,NaN,NaN,NaN,NaN

In [5]:
kor_overall_df.iloc[6:, :].head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
1985/01,NaN,NaN,"6,685,546",NaN,51.94,26.06,29.052,NaN,NaN,127.37,NaN,NaN,70.49,NaN,NaN,830.30,NaN,NaN,NaN
1985/02,NaN,NaN,"6,843,700",NaN,51.89,26.10,29.259,NaN,NaN,126.79,NaN,NaN,70.34,NaN,NaN,836.90,NaN,NaN,NaN
1985/03,NaN,NaN,"6,659,195",NaN,51.68,26.24,29.289,NaN,NaN,126.42,NaN,NaN,70.12,NaN,NaN,848.97,NaN,NaN,NaN
1985/04,NaN,NaN,"6,601,523",NaN,51.94,26.52,29.319,NaN,NaN,126.65,NaN,NaN,70.27,NaN,NaN,859.34,NaN,NaN,NaN
1985/05,NaN,NaN,"6,541,708",NaN,51.89,26.85,29.526,NaN,NaN,126.04,NaN,NaN,70.09,NaN,NaN,868.92,NaN,NaN,NaN